name: "Find Intermediates Base"
description: "Find the first commit, from last 5, to have successfully cached its build artifacts"
inputs:
  cache-url:
    description: "The URL of the Nix binary cache to fetch previous intermediates from"
    required: true
  package-name:
    description: "The `packages.<name>` flake output to incrementally build using previous intermediates. Leave empty to use `default`"
    required: false
    default: "default"
outputs:
  commit-hash:
    description: "The commit hash of which the build artifacts are cached for flake's `packages` output with the name `inputs.package-name`"
    value: ${{ steps.find_intermediates.outputs.base_commit }}
runs:
  using: "composite"
  steps:
    - name: Find base commit for incremental build
      id: find_intermediates
      if: github.event_name == 'pull_request'
      shell: bash
      run: |
        BASE_COMMIT=$(sh $GITHUB_ACTION_PATH/find_intermediates_base.sh ${{ github.repository }} ${{ inputs.package-name }} ${{ inputs.cache-url }})
        if [ -n "$BASE_COMMIT" ]; then
          echo "base_commit=$BASE_COMMIT" >> $GITHUB_OUTPUT
        else
          echo "base_commit=" >> $GITHUB_OUTPUT
        fi


