name: "CI"
on:
  # Run only when pushing to main branch, and making PRs
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Install omnix and attic-client
        run: | 
          nix profile install nixpkgs#omnix nixpkgs#attic-client
          nix --version
      - name: Setup Attic
        run: |
          attic login chutney https://cache.nixos.asia ${{ secrets.ATTIC_LOGIN_TOKEN }}
          attic use chutney:oss
      - name: Find first intermediates from last 5 commits
        id: check_commits
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          SUCCESSFUL_COMMIT=""
          echo $(git log -n 5 --pretty=%H)
          for COMMIT in $(git log -n 5 --pretty=%H); do
            echo "Testing commit $COMMIT"
            # A workaround for runners not having access to private repos when the Git SSH url is used
            git checkout $COMMIT
            if nix path-info $(nix eval .#default.intermediates.outPath | tr -d '"') --store https://cache.nixos.asia/oss; then
              SUCCESSFUL_COMMIT=$COMMIT
              echo "Intermediates exist for $COMMIT"
              break
            else
              echo "Intermediates do not exist for $COMMIT"
            fi
            echo ${{ github.sha }}
            git checkout ${{ github.sha }}
          done
          if [ -n "$SUCCESSFUL_COMMIT" ]; then
            echo "successful_commit=$SUCCESSFUL_COMMIT" >> $GITHUB_OUTPUT
          else
            echo "None of the previous 5 commits have build intermediates"
          fi
      - name: Incremental Build
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          if [ -z "${{ steps.check_commits.outputs.successful_commit }}" ]; then
            om ci
          else
            # A workaround for runners not having access to private repos when the Git SSH url is used
            WORKTREE_DIR="temp-worktree"
            git worktree add $WORKTREE_DIR ${{ steps.check_commits.outputs.successful_commit }}
            om ci run -- --override-input "flake/incremental" "path:$WORKTREE_DIR"
            # cleanup
            git worktree remove ${{ steps.worktree.outputs.worktree_dir }}
          fi
      # Perform a full build only on the main branch
      - name: Full Build
        if: ${{ github.event_name == 'push' }}
        run: om ci
      - name: Attic Push
        run: attic push chutney:oss result

