name: "CI"
on:
  # Run only when pushing to master branch, and making PRs
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Install omnix and attic-client
        run: | 
          nix profile install nixpkgs#omnix nixpkgs#attic-client
          nix --version
      - name: Attic login
        run: attic login chutney https://cache.nixos.asia ${{ secrets.ATTIC_LOGIN_TOKEN }}
      - name: Attic use
        run: attic use chutney:oss
      - name: Find first intermediates from last 5 commits
        id: check_commits
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          SUCCESSFUL_COMMIT=""
          for COMMIT in $(git log -n 5 --pretty=%H); do
            echo "Testing commit $COMMIT"
            git checkout $COMMIT
            if nix path-info $(nix eval .#default.intermediates.outPath | tr -d '"') --store https://cache.nixos.asia/oss; then
              SUCCESSFUL_COMMIT=$COMMIT
              echo "Intermediates exist for $COMMIT"
              break
            else
              echo "Intermediates do not exist for $COMMIT"
            fi
            git checkout ${{ github.head_ref }}
          done
          if [ -n "$SUCCESSFUL_COMMIT" ]; then
            echo "successful_commit=$SUCCESSFUL_COMMIT" >> $GITHUB_OUTPUT
          else
            echo "None of the previous 5 commits have build intermediates"
          fi
      # This stage is required for private repos
      - name: Add worktree for the commit with intermediates 
        id: worktree
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          WORKTREE_DIR="temp-worktree"
          git worktree add $WORKTREE_DIR ${{ steps.check_commits.outputs.successful_commit }}

          echo "worktree_dir=$WORKTREE_DIR" >> $GITHUB_OUTPUT
      - name: Incremental Build
        if: ${{ github.event_name == 'pull_request' }}
        run: om ci run -- --override-input "flake/incremental" "path:${{ steps.worktree.outputs.worktree_dir }}"
      - name: Cleanup worktree 
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git worktree remove ${{ steps.worktree.outputs.worktree_dir }}
      - name: Full Build
        if: ${{ github.event_name == 'push' }}
        run: om ci
      - name: Attic push
        run: attic push chutney:oss result

