name: "CI"
on:
  # Run only when pushing to master branch, and making PRs
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Install omnix
        run: | 
          nix --accept-flake-config profile install "github:juspay/omnix"
          nix profile install nixpkgs#attic-client
          nix --version
      - name: Attic login
        run: attic login chutney https://cache.nixos.asia ${{ secrets.ATTIC_LOGIN_TOKEN }}
      - name: Attic use
        run: attic use chutney:oss
      - name: Build all flake outputs
        run: om ci
      - name: Attic push
        run: attic push chutney:oss result

